28-07-2023 15:01:54 - [2023-07-28 15:01] ## Acessando diário em http://esaj.tjam.jus.br/cdje/downloadCaderno.do?dtDiario=31/05/2021&cdCaderno=1
28-07-2023 15:01:54 - DJAM_Caderno_Administrativo_2021_05_31.pdf já existe. Pulando...
28-07-2023 15:01:54 - [2023-07-28 15:01] ## Acessando diário em http://esaj.tjam.jus.br/cdje/downloadCaderno.do?dtDiario=01/06/2021&cdCaderno=1
28-07-2023 15:01:58 - [2023-07-28 15:01] ## Erro: Número de tentativas de download excedidas: HTTPSConnectionPool(host='admin-saj-sg.tjam.jus.br', port=443): Max retries exceeded with url: /?dtDiario=01/06/2021&cdCaderno=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f18329ede48>: Failed to establish a new connection: [Errno -2] Name or service not known',))
28-07-2023 15:01:58 - [2023-07-28 15:01] ## Acessando diário em http://esaj.tjam.jus.br/cdje/downloadCaderno.do?dtDiario=01/06/2021&cdCaderno=1
28-07-2023 15:01:59 - [2023-07-28 15:01] ## Erro: Número de tentativas de download excedidas: HTTPSConnectionPool(host='admin-saj-sg.tjam.jus.br', port=443): Max retries exceeded with url: /?dtDiario=01/06/2021&cdCaderno=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f18329ed518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
28-07-2023 15:01:59 - [2023-07-28 15:01] ## Acessando diário em http://esaj.tjam.jus.br/cdje/downloadCaderno.do?dtDiario=01/06/2021&cdCaderno=1
28-07-2023 15:02:00 - [2023-07-28 15:02] ## Erro: Número de tentativas de download excedidas: HTTPSConnectionPool(host='admin-saj-sg.tjam.jus.br', port=443): Max retries exceeded with url: /?dtDiario=01/06/2021&cdCaderno=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1832a27710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
28-07-2023 15:02:00 - [2023-07-28 15:02] ## Acessando diário em http://esaj.tjam.jus.br/cdje/downloadCaderno.do?dtDiario=01/06/2021&cdCaderno=1
28-07-2023 15:02:01 - [2023-07-28 15:02] ## Erro: Número de tentativas de download excedidas: HTTPSConnectionPool(host='admin-saj-sg.tjam.jus.br', port=443): Max retries exceeded with url: /?dtDiario=01/06/2021&cdCaderno=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f18329ed2e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
28-07-2023 15:02:01 - [2023-07-28 15:02] ## Acessando diário em http://esaj.tjam.jus.br/cdje/downloadCaderno.do?dtDiario=01/06/2021&cdCaderno=1
28-07-2023 15:02:01 - [2023-07-28 15:02] ## Erro: Número de tentativas de download excedidas: HTTPSConnectionPool(host='admin-saj-sg.tjam.jus.br', port=443): Max retries exceeded with url: /?dtDiario=01/06/2021&cdCaderno=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1832a27e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
28-07-2023 15:02:01 - [2023-07-28 15:02] ## Acessando diário em http://esaj.tjam.jus.br/cdje/downloadCaderno.do?dtDiario=01/06/2021&cdCaderno=1
28-07-2023 15:02:02 - [2023-07-28 15:02] ## Erro: Número de tentativas de download excedidas: HTTPSConnectionPool(host='admin-saj-sg.tjam.jus.br', port=443): Max retries exceeded with url: /?dtDiario=01/06/2021&cdCaderno=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1832a31940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
28-07-2023 15:02:02 - [2023-07-28 15:02] ## Acessando diário em http://esaj.tjam.jus.br/cdje/downloadCaderno.do?dtDiario=01/06/2021&cdCaderno=1
28-07-2023 15:02:03 - [2023-07-28 15:02] ## Erro: Número de tentativas de download excedidas: HTTPSConnectionPool(host='admin-saj-sg.tjam.jus.br', port=443): Max retries exceeded with url: /?dtDiario=01/06/2021&cdCaderno=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1832a31978>: Failed to establish a new connection: [Errno -2] Name or service not known',))
28-07-2023 15:02:03 - [2023-07-28 15:02] ## Acessando diário em http://esaj.tjam.jus.br/cdje/downloadCaderno.do?dtDiario=01/06/2021&cdCaderno=1
28-07-2023 15:02:04 - [2023-07-28 15:02] ## Erro: Número de tentativas de download excedidas: HTTPSConnectionPool(host='admin-saj-sg.tjam.jus.br', port=443): Max retries exceeded with url: /?dtDiario=01/06/2021&cdCaderno=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1832a3abe0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
28-07-2023 15:02:04 - [2023-07-28 15:02] ## Acessando diário em http://esaj.tjam.jus.br/cdje/downloadCaderno.do?dtDiario=01/06/2021&cdCaderno=1
28-07-2023 15:02:04 - [2023-07-28 15:02] ## Erro: Número de tentativas de download excedidas: HTTPSConnectionPool(host='admin-saj-sg.tjam.jus.br', port=443): Max retries exceeded with url: /?dtDiario=01/06/2021&cdCaderno=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1832a3a8d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
28-07-2023 15:02:04 - [2023-07-28 15:02] ## Acessando diário em http://esaj.tjam.jus.br/cdje/downloadCaderno.do?dtDiario=01/06/2021&cdCaderno=1
28-07-2023 15:02:05 - [2023-07-28 15:02] ## Erro: Número de tentativas de download excedidas: HTTPSConnectionPool(host='admin-saj-sg.tjam.jus.br', port=443): Max retries exceeded with url: /?dtDiario=01/06/2021&cdCaderno=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1832a312e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
28-07-2023 15:22:46 - ########### INÍCIO ROBÔ DJAM ###########
28-07-2023 15:23:49 - ########### INÍCIO ROBÔ DJAM ###########
28-07-2023 15:32:19 - ########### INÍCIO ROBÔ DJAM ###########
